steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: "bash"
  args:
    - '-c'
    - |
        cd konica-minolta--fed/src
        ls
        rm *.xml
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'gs://bucket-km-test/b.xml', 'konica-minolta--fed/src/b.xml','cp','gs://bucket-km-test/c.xml','konica-minolta--fed/src/c.xml']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: "bash"
  args:
    - '-c'
    - |
        cd konica-minolta--fed/src
        ls
