steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: "bash"
  args:
    - '-c'
    - |
        cd konica-minolta--fed/src
        ls
        rm *.xml
        curl 'https://github.com/mani-sadaindia/poc-xml-host/blob/main/note1.xml' -o sitemap-us.xml --create-dirs
        curl 'https://github.com/mani-sadaindia/poc-xml-host/blob/main/note2.xml' -o sitemap-be.xml --create-dirs
        for((i=1; i <=12 ; i++))
        do
          curl 'https://github.com/mani-sadaindia/poc-xml-host/blob/main/note2.xml' -o sitemap-$i.xml --create-dirs
        done
        ls
        cat sitemap-us.xml
        cat sitemap-12.xml
        cat sitemap-1.xml

